### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Maximus7474** [ShopFusionTebex/dl_fishing_warehouse#2]
Presume it was accidental or I might of missed something but the MLO won't load properly.
As there's no stream folder so it doesn't pop up on first load. I'll let you do it and not PR it

However I'm not sure about the following:
![image](https://github.com/user-attachments/assets/9127cd0a-36c1-4ed6-b8e9-47e4540d0752)
![image](https://github.com/user-attachments/assets/4bf14aef-f8e1-49af-9287-a63bd169b9ec)
![image](https://github.com/user-attachments/assets/d87ee421-32f9-4e7b-9c2b-eb84ef506e06)
![image](https://github.com/user-attachments/assets/0e222a29-b82e-4ca1-8f85-113e52d0fe0f)

Love the work, well designed and very appreciated that it's free and open source !

**Comment by ShopFusionTebex** [comment]
Hello, did you manage to open the stream directory and transfer the files? Unfortunately, I couldn't put them in this directory because too many files did not allow me to do so. I am attaching screenshots of the correct diagram
![image](https://github.com/user-attachments/assets/72f5f6e0-c617-4cd4-a7d5-53d5fc5f3154)
![image](https://github.com/user-attachments/assets/1c81262f-29e3-4d4f-b98c-da26976134e0)
![image](https://github.com/user-attachments/assets/82683863-7004-4052-ac9a-45c17ee618cd)

**Comment by Maximus7474** [comment]
Yeah, I've got that structure as well
![image](https://github.com/user-attachments/assets/7f5dc8d9-aa4a-4abf-96a5-fd664735db18)

**Comment by Maximus7474** [comment]
Missclick sorry

**Comment by ShopFusionTebex** [comment]
Try downloading it for free from my website: https://shopfusion.tebex.io/category/mlo . What version of artifact do you have?

**Comment by Maximus7474** [comment]
I'm on 7290 and game build 3095
Will give it a try

**Comment by Maximus7474** [comment]
Extremely odd, works fine the encrypted asset

**Comment by ShopFusionTebex** [comment]
Or I would have to mess something up in the files on github
